
---
title: "Exploring Data Analysis"
author: "Arka Bose"
format: pdf
---

```{r}
data <- read.csv("../Data/data.csv")
data2 <- read.csv("../Data/500cities.csv")





```

```{r}
url <- "https://data.cdc.gov/resource/mb5y-ytti.csv"
destination_file <- "../Data/test.csv"

# Download the file
download.file(url, destination_file, method = "auto")
```


```{r}
library(dplyr)
# Assuming your data frame is named 'data'

# Step 1: Convert columns to strings and pad with leading zeros
data$STATEFP <- sprintf("%02d", as.numeric(data$STATEFP))
data$COUNTYFP <- sprintf("%03d", as.numeric(data$COUNTYFP))
data$TRACTCE <- sprintf("%06d", as.numeric(data$TRACTCE))

# Step 2: Concatenate the padded columns
data$TractFIPS <- paste0(data$STATEFP, data$COUNTYFP, data$TRACTCE)

# Step 3: Convert the concatenated string to integer
data$TractFIPS <- as.numeric(data$TractFIPS)

```



```{r}
colnames(data)
```


```{r}
# Assuming your data frames are named 'data1' and 'data2'
averaged_data <- data %>%
  group_by(TractFIPS) %>%
  summarise(NatWalkInd = mean(NatWalkInd, na.rm = TRUE)) %>%
  ungroup()

```

```{r}
merged_data <- merge(averaged_data, data2, by = "TractFIPS", all.x = TRUE, all.y = TRUE)
merged_data <- merged_data %>%
  filter(StateAbbr == "CA")
```



































```{r}
library(sf)
library(dplyr)
library(ggplot2)
spatial_data <- st_read("../Data/shapes/ca_tract")

spatial_data$TractFIPS <- as.numeric(spatial_data$GEOID)
merged_data <- merge(merged_data, spatial_data, by = "TractFIPS", all.x = TRUE, all.y = TRUE)

merged_data <- na.omit(merged_data)

```

```{r}
merged_sf <- st_as_sf(merged_data)
ggplot() +
  geom_sf(data = merged_sf, aes(fill = NatWalkInd)) +
scale_fill_gradientn(colours = terrain.colors(8),
                       limits = c(0, 20),
                       breaks = c(0, 10, 20))

```
```{r}
colnames(merged_data)
```


```{r}
ggplot() +
  geom_sf(data = merged_sf, aes(fill = DIABETES_CrudePrev)) +
  scale_fill_gradientn(colours = terrain.colors(8),
                       limits = c(0, 28),
                       breaks = c(0, 12.5, 25)) 
```



```{r}

merged_data$geometry
```
```{r}
merged_sf <- st_as_sf(merged_data)

# Plot the spatial data with ggplot
ggplot() +
  geom_sf(data = merged_sf, aes(fill = NatWalkInd)) 
```
```{r}
spatial_data <- st_read("../Data/shapes/ny")

data <- data %>%
  group_by(BLKGRPCE) %>%
  summarise_all(mean, na.rm = TRUE)



merged_data <- merge(data, spatial_data, by = "BLKGRPCE")


merged_sf <- st_as_sf(merged_data)

# Plot the spatial data with ggplot
ggplot() +
  geom_sf(data = merged_sf, aes(fill = NatWalkInd)) 
```


```{r}
data3 <- read.csv("../Data/500cities.csv")


library(stringr)
library(dplyr)
library(sf)
library(ggplot2)
regex_pattern <- "\\((-?\\d+\\.\\d+),\\s*(-?\\d+\\.\\d+)\\)"
data3$latitude =  as.numeric(str_match(data3$GeoLocation, regex_pattern)[, 2])
data3$longitude =  as.numeric(str_match(data3$GeoLocation, regex_pattern)[, 3])
options(digits = 10)
data3$latitude


filtered_df_subset <- subset(data3, DataValueTypeID == "CrdPrv")
ggplot(filtered_df_subset, aes(x = longitude, y = latitude,color=Data_Value)) +
  geom_point() +
  ggtitle("Spatial Plot with Latitude and Longitude") +
  xlab("Longitude") +
  ylab("Latitude") +
  theme_minimal()


data3$Short_Question_Text

```
Based on this data set, we can see that the the crude prevalence of type II diabetes seems to be consistently low along the west coast (California and Washington area). This may be because those areas promote healthy lifestyles and have areas to go exercise or hike
